"""Add Business model

Revision ID: 5a5c6c3537a9
Revises: 39580e159ea8
Create Date: 2024-05-24 18:39:59.409607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5c6c3537a9'
down_revision = '39580e159ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('business_type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('machine_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=128), nullable=True))
        batch_op.create_foreign_key(None, 'business', ['business_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=128), nullable=True))
        batch_op.create_foreign_key(None, 'business', ['business_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('machine_booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('business_id')

    op.drop_table('business')
    # ### end Alembic commands ###
